N_TRY_PER_ENDPOINT: 100
N_IMAGE_PER_PROMPT: 4
NEGATIVE_PROMPT: "ugly, blurry, poor quality"
TOPICS:
  animated_style:
    prefix: "a animated image of"
  artistic_style:
    prefix: "a artistic, artstation image of"
  landscape_style:
    prefix: "a landscape image of"
  portrait_style:
    prefix: "a portrait image of"
  realistic_photo_style:
    prefix: "a realistic photo of"
ENDPOINTS:
  sdxl:
    - "stabilityai/stable-diffusion-xl-base-1.0"
    - "segmind/SSD-1B"
  sd:
    - "stablediffusionapi/edge-of-realism"
    - "stablediffusionapi/rev-anim"
    - "stablediffusionapi/realistic-vision-v51"
    - "dreamlike-art/dreamlike-photoreal-2.0"
    - "stabilityai/stable-diffusion-2-1"
    - "CompVis/stable-diffusion-v1-4"
    - "runwayml/stable-diffusion-v1-5"
DEVICE: "cuda"
SAVE_DIR: "outputs"
