N_TRY_PER_ENDPOINT: 100
N_IMAGE_PER_PROMPT: 4
NEGATIVE_PROMPT: "ugly, blurry, poor quality, nsfw, sexy, nude, naked"
TOPICS:
  animated_style:
    prefix: "a anime, artwork, animated illustration, high quality image of"
  artistic_style:
    prefix: "a artistic, artstation, painting, high quality, beautiful image of"
  landscape_style:
    prefix: "a landscape, scenic, nature, high quality, majestic image of"
  portrait_style:
    prefix: "a portrait, face, realistic, brilliant, pretty image of"
  realistic_photo_style:
    prefix: "a realistic, photo, genuine, captured, photography image of"
ENDPOINTS:
  sd:
    - "stablediffusionapi/edge-of-realism"
    - "stablediffusionapi/rev-anim"
    - "stablediffusionapi/realistic-vision-v51"
    - "dreamlike-art/dreamlike-photoreal-2.0"
    - "stabilityai/stable-diffusion-2-1"
    - "CompVis/stable-diffusion-v1-4"
    - "runwayml/stable-diffusion-v1-5"
  sdxl:
    - "stabilityai/stable-diffusion-xl-base-1.0"
    - "segmind/SSD-1B"
DEVICE: "cuda"
SAVE_DIR: "outputs"
