prompter:
  target: ig_rewarding.models.PromptGenerator
  params:
    chroma_db_config:
      root_path: chroma_db/
      collection_name: "diffusiondb"
      prompt_table_url: "https://huggingface.co/datasets/poloclub/diffusiondb/resolve/main/metadata.parquet"
      n_neighbors: 500

rewarder:
  target: ig_rewarding.models.TextToImageRewarder
  params:
    rewarder_configs:
      prompt_alignment_rewarder:
        target: ig_rewarding.models.TextAlignmentRewardModel
        params:
          name: "ImageReward-v1.0"
          device: "cuda"
        weight: 1
      diversity_rewarder:
        target: ig_rewarding.models.DiversityRewardModel
        params:
          model: "resnet18"
          pretrained: true
          device: "cuda"
        weight: 0.15
      clip_interrogator_rewarder:
        target: ig_rewarding.models.CLIPInterrogatorRewardModel
        params:
          ci_config:
            clip_model_name: "ViT-L-14/openai"
            caption_model_name: "blip-large"
            device: "cuda"
          bert_scorer_config:
            model_type: "microsoft/deberta-xlarge-mnli"
            device: "cuda"
            lang: "en"
            rescale_with_baseline: true
        weight: 0.15
