rewarder:
  target: ig_rewarding.models.TextToImageRewarder
  params:
    prompt_alignment_rewarder_config:
      target: ig_rewarding.models.TextAlignmentRewardModel
      params:
        name: "ImageReward-v1.0"
    diversity_rewarder_config:
      target: ig_rewarding.models.DiversityRewardModel
      params:
        model: "resnet18"
        pretrained: true
