prompter:
  target: ig_rewarding.models.PromptGenerator
  params:
    chroma_db_config:
      root_path: chroma_db/
      collection_name: "diffusiondb"
      prompt_table_url: "https://huggingface.co/datasets/THUDM/ImageRewardDB/resolve/main/metadata-train.parquet"

rewarder:
  target: ig_rewarding.models.TextToImageRewarder
  params:
    rewarder_configs:
      clip_aesthetic_rewarder:
        target: ig_rewarding.models.CLIPAestheticRewardModel
        params:
          device: "cuda"
        weight: 0.0125
      pick_rewarder:
        target: ig_rewarding.models.PickRewardModel
        params:
          device: "cuda"
        weight: 0.1
      image_rewarder:
        target: ig_rewarding.models.ImageRewardModel
        params:
          name: "ImageReward-v1.0"
          device: "cuda"
        weight: 1
      hps_v2_rewarder:
        target: ig_rewarding.models.HPSv2
        params:
          device: "cuda"
        weight: 0.1
